In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import plotly.graph_objs as go
from plotly.offline import iplot
sns.set()
pd.options.display.max_columns = 999

In [2]:
data = pd.read_excel('data/qatar-imports-2019-2024.xlsx')

In [5]:
data.head()

,Year,Quarter,Month,HS8,التفاصيل,Details,دولة المنشأ,Country of Origin,Quantity,Weight (KG),Value (QR)
0,2024,Q1,2,3071100,المحار، حي أو طازج أو مبرد,"Oysters,Live Fresh Or Chilled",سلطنة عمان,Oman,120,2400.00,23928.000
1,2024,Q1,2,3074200,حبار وسبيدج ، حي أو طازج أو مبرد,"Live, fresh or chilled of Cuttle fish and squid",سلطنة عمان,Oman,2613,5900.00,57282.635
2,2024,Q1,2,4012030,ألبان وقشدة، غير مركزة ولا محتوية على سكر مضاف...,"Long Life Milk , In Packing Exceeding 1 L",المانيا,Germany,1033,3871.56,55240.050
3,2024,Q1,2,4015030,لبن (حليب) طويل الأجل بعبوات تزيد سعتها عن لتر...,"Long Life Milk, In Containers Exceeding 1 Litr...",فرنسا,France,4410,1662.70,123387.377
4,2024,Q1,2,4022190,غيرها من الحليب المسحوق,"Milk & Cream, Other",سلطنة عمان,Oman,9775,114595.80,2375937.278

In [6]:
print(data.shape)

(830353, 11)

In [8]:
data['HS8'].nunique()

7140

In [9]:
print(data.isnull().sum())

Year                  0
Quarter               0
Month                 0
HS8                   0
التفاصيل              0
Details               0
دولة المنشأ          72
Country of Origin    72
Quantity              0
Weight (KG)           0
Value (QR)            0
dtype: int64

In [18]:
data[data['Country of Origin'].isna()].head()

,Year,Quarter,Month,HS8,التفاصيل,Details,دولة المنشأ,Country of Origin,Quantity,Weight (KG),Value (QR)
39194,2024,Q1,3,0,أخرى القيم أقل من 20 ألف ريال قطري,Other Value Less Than 20 Thousand QR,NaN,NaN,13217640,8.021877e+06,1.216905e+08
51385,2024,Q3,9,0,أخرى القيم أقل من 20 ألف ريال قطري,Other Value Less Than 20 Thousand QR,NaN,NaN,10923918,7.597076e+06,1.250720e+08
56728,2022,Q3,8,0,أخرى تشمل السلع التي قيمتها أقل من 50 ألف ريال...,Other Include Items Which Value Less Than 50 T...,NaN,NaN,27978542,1.643947e+07,2.823298e+08
69742,2023,Q3,9,0,أخرى تشمل السلع التي قيمتها أقل من 50 ألف ريال...,Other Include Items Which Value Less Than 50 T...,NaN,NaN,23734037,1.859995e+07,2.707009e+08
75477,2023,Q3,8,0,أخرى تشمل السلع التي قيمتها أقل من 50 ألف ريال...,Other Include Items Which Value Less Than 50 T...,NaN,NaN,35935222,1.904991e+07,2.740641e+08

In [11]:
print(data.dtypes)

Year                   int64
Quarter               object
Month                  int64
HS8                    int64
التفاصيل              object
Details               object
دولة المنشأ           object
Country of Origin     object
Quantity               int64
Weight (KG)          float64
Value (QR)           float64
dtype: object

In [20]:
print(data.loc[data['HS8'] == '0', 'Country of Origin'].unique())

[]

In [21]:
data = data.dropna(subset=['Country of Origin'])

In [22]:
print(data.isna().sum())

Year                 0
Quarter              0
Month                0
HS8                  0
التفاصيل             0
Details              0
دولة المنشأ          0
Country of Origin    0
Quantity             0
Weight (KG)          0
Value (QR)           0
dtype: int64

In [23]:
data.drop(columns=['التفاصيل', 'دولة المنشأ'], inplace=True)

/var/folders/5s/mv4171b97vd_bhbvhbg7yx6h0000gn/T/ipykernel_87360/1409997919.py:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [26]:
data.columns

Index(['Year', 'Quarter', 'Month', 'HS8', 'Details', 'Country of Origin',
       'Quantity', 'Weight (KG)', 'Value (QR)'],
      dtype='object')

In [27]:
data.dtypes

Year                   int64
Quarter               object
Month                  int64
HS8                    int64
Details               object
Country of Origin     object
Quantity               int64
Weight (KG)          float64
Value (QR)           float64
dtype: object

In [28]:
data['Date'] = pd.to_datetime(data['Year'].astype(str) + '-' + data['Month'].astype(str) + '-01')

/var/folders/5s/mv4171b97vd_bhbvhbg7yx6h0000gn/T/ipykernel_87360/3636204238.py:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [29]:
data.dtypes

Year                          int64
Quarter                      object
Month                         int64
HS8                           int64
Details                      object
Country of Origin            object
Quantity                      int64
Weight (KG)                 float64
Value (QR)                  float64
Date                 datetime64[ns]
dtype: object

In [31]:
print(data.isna().sum())

Year                 0
Quarter              0
Month                0
HS8                  0
Details              0
Country of Origin    0
Quantity             0
Weight (KG)          0
Value (QR)           0
Date                 0
dtype: int64

In [32]:
data["PricePerUnit"] = data["Value (QR)"] / data["Quantity"]
data["PricePerKG"] = data["Value (QR)"] / data["Weight (KG)"]

In [33]:
data.columns

Index(['Year', 'Quarter', 'Month', 'HS8', 'Details', 'Country of Origin',
       'Quantity', 'Weight (KG)', 'Value (QR)', 'Date', 'PricePerUnit',
       'PricePerKG'],
      dtype='object')

In [34]:
data.dtypes

Year                          int64
Quarter                      object
Month                         int64
HS8                           int64
Details                      object
Country of Origin            object
Quantity                      int64
Weight (KG)                 float64
Value (QR)                  float64
Date                 datetime64[ns]
PricePerUnit                float64
PricePerKG                  float64
dtype: object

In [38]:
data.to_excel("new_data.xlsx", index=False)